# Generated by Django 5.2 on 2025-09-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_public__54fddc_idx',
            old_name='api_note_public__idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_updated_9a6ec7_idx',
            old_name='api_note_updated__idx',
        ),
    ]
